### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2153]
## What went wrong? 😲
 
On the demo server, add an expiry date to an Inbound Shipment line and save.
Try to edit that line.. this is giving and error screen (oops!)

with this in the console:

```
285f8dc30c48b4e08061.js:102 RangeError: Invalid time value
    at A (285f8dc30c48b4e08061.js:102:318658)
    at Dt.formatByString (285f8dc30c48b4e08061.js:102:257070)
    at Dt.format (285f8dc30c48b4e08061.js:102:257002)
    at openDatePickerDialogue (d58b2f87a2ca6c68eda1.js:2:276593)
    at $ (d58b2f87a2ca6c68eda1.js:2:242873)
    at d58b2f87a2ca6c68eda1.js:2:175427
    at Ea (285f8dc30c48b4e08061.js:102:632153)
    at ks (285f8dc30c48b4e08061.js:102:642202)
    at El (285f8dc30c48b4e08061.js:102:691032)
```

where the expiry date is

```
                        "expiryDate": "2025-03-31",
```

Editing a line which has no expiry date is fine.

## Expected behaviour 🤔
No error

## How to Reproduce 🔨

Steps to reproduce the behaviour:

As above, try to edit an existing line which has an expiry date set.

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment]
Adding `value={DateUtils.getDateOrNull(props.value)}` to the `BaseDatePickerInput` fixes issue

**Comment by nisha-dangol** [comment]
Looks good in v2.1; moving to Done.
